version: "3"

services:
  backend:
    build: ./php
  production-nginx-container:
    container_name: 'production-nginx-container'
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./production.conf:/etc/nginx/conf.d/default.conf
      - ./production-site:/usr/share/nginx/html
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/pwp/etc/letsencrypt/live/dont-blindly-copy-past.face-palm/fullchain.pem:/etc/letsencrypt/live/dont-blindly-copy-past.face-palm/fullchain.pem
      - /docker-volumes/pwp/etc/letsencrypt/live/dont-blindly-copy-past.face-palm/privkey.pem:/etc/letsencrypt/live/dont-blindly-copy-past.face-palm/privkey.pem


